#!/bin/bash
#Installatie DRBL CloneZilla

set -o errexit # abort on nonzero exitstatus
set -o nounset # abort on unbound variable

#Download and install

rm -f GPG-KEY-DRBL; wget http://drbl.org/GPG-KEY-DRBL; rpm --import GPG-KEY-DRBL
gpg --keyserver pgp.mit.edu --recv-key D7E8DF3A
gpg -a --export D7E8DF3A > GPG-KEY-DRBL; rpm --import GPG-KEY-DRBL
https://sourceforge.net/projects/drbl/files/drbl_stable/2.22.5/drbl-2.22.5-drbl1.noarch.rpm/download
sudo yum install perl
rpm -Uvh download --nodeps

#Configuration
# Run DRBL Install Script
# Note: 'yes "" | <cmd>' just hits enter for the drblsrv command when prompted
yes "" | drblsrv -i --netinstall n --console-output n --upgrade_system n --client_archi 2 --client_kernel_from 1


# Run DRBL Script to setup environment for imaging with CloneZilla
drbl4imp -b -c 2 -p 42 -k 2 -r 1 -u 2 -z 3
drbl-ocs -b -l en_US.UTF-8 -y1 -p poweroff select_in_client
