# site.yml
---
- hosts: production
  remote_user: vagrant
  serial: 1
  roles:
    - common
    - docker
    - docker-compose
    - consul
    - registrator
    - consul-template
    - nginx
    - java
    - jenkins-node


- hosts: jenkinsCD
  remote_user: vagrant
  serial: 1
  roles:
    - consul-template
    - jenkins
    - java
    - jenkins-node




