- hosts: localhost
  remote_user: vagrant
  serial: 1
  roles:
    - common
    - docker
    - docker-compose
    - docker-flow
    - jenkins
    
- hosts: prod
  remote_user: vagrant
  serial: 1
  roles:
    - common
    - docker
    - docker-compose    
    - nginx
- hosts: jenkins-node
  remote_user: vagrant
  serial: 1
  roles:
    - java
    - jenkins-node

